database:
    config:
        env: jdbc-dev
spring:
    datasource:
        druid:
            url: ${jdbc.url}
            username: ${jdbc.username}
            password: ${jdbc.password}
            initial-size: 5
            max-active: 20
            min-idle: 5
            max-wait: 10000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            max-open-prepared-statements: 20
            validation-query: SELECT 1 FROM DUAL
            validation-query-timeout: 1000
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000

mybatis:
    type-aliases-package: xyz.ivyxjc.pubg.system.common.dao
    mapper-locations: classpath:mybatis/*.xml