server:
    port: 27001

database:
    config:
        env: jdbc-dev

dubbo:
    application:
        name: remediation-service
    registry:
        address:  zookeeper://127.0.0.1:2181
    protocol:
        port: -1
        name: dubbo
    scan:
        base-packages: xyz.ivyxjc.pubg.remediation.impl


spring:
    datasource:
        druid:
            url: ${jdbc.url}
            username: ${jdbc.username}
            password: ${jdbc.password}
            initial-size: 1
            max-active: 5
            min-idle: 5
            max-wait: 10000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            max-open-prepared-statements: 20
            validation-query: SELECT 1 FROM DUAL
            validation-query-timeout: 1000
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000