CREATE TABLE `RAW_MESSAGE`
(
    `GUID` INT8 NOT NULL,
    `MESSAGE`         TEXT        NOT NULL,
    `DB_CREATED_AT`   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `DB_CREATED_BY`   VARCHAR(20) NULL,
    `DB_CREATED_FROM` VARCHAR(20) NULL,
    `DB_UPDATED_AT`   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    `DB_UPDATED_BY`   VARCHAR(20) NULL,
    `DB_UPDATED_FROM` VARCHAR(20) NULL,
    PRIMARY KEY (`GUID`),
    INDEX `RAW_MESSAGE_NX1` (`DB_CREATED_AT` DESC)
)
    ENGINE = InnoDB;